///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WeatherAPIDataWeather {
/*
{
  "icon": "c01d",
  "code": 800,
  "description": "Clear Sky"
} 
*/

  String? icon;
  int? code;
  String? description;

  WeatherAPIDataWeather({
    this.icon,
    this.code,
    this.description,
  });
  WeatherAPIDataWeather.fromJson(Map<String, dynamic> json) {
    icon = json["icon"]?.toString();
    code = json["code"]?.toInt();
    description = json["description"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["icon"] = icon;
    data["code"] = code;
    data["description"] = description;
    return data;
  }
}

class WeatherAPIData {
/*
{
  "moonrise_ts": 1634594272,
  "wind_cdir": "W",
  "rh": 60,
  "pres": 1009.29,
  "high_temp": 19.9,
  "sunset_ts": 1634596376,
  "ozone": 293.405,
  "moon_phase": 0.985026,
  "wind_gust_spd": 12.5,
  "snow_depth": 0,
  "clouds": 1,
  "ts": 1634529660,
  "sunrise_ts": 1634556206,
  "app_min_temp": 8.8,
  "wind_spd": 3.17652,
  "pop": 0,
  "wind_cdir_full": "west",
  "slp": 1019.4,
  "moon_phase_lunation": 0.43,
  "valid_date": "2021-10-18",
  "app_max_temp": 18.9,
  "vis": 24.096,
  "dewpt": 6.1,
  "snow": 0,
  "uv": 5.33343,
  "weather": {
    "icon": "c01d",
    "code": 800,
    "description": "Clear Sky"
  },
  "wind_dir": 277,
  "max_dhi": null,
  "clouds_hi": 0,
  "precip": 0,
  "low_temp": 8.8,
  "max_temp": 19.9,
  "moonset_ts": 1634552290,
  "datetime": "2021-10-18",
  "temp": 14.6,
  "min_temp": 8.7,
  "clouds_mid": 0,
  "clouds_low": 1
} 
*/

  int? moonriseTs;
  String? windCdir;
  int? rh;
  double? pres;
  double? highTemp;
  int? sunsetTs;
  double? ozone;
  double? moonPhase;
  double? windGustSpd;
  int? snowDepth;
  int? clouds;
  int? ts;
  int? sunriseTs;
  double? appMinTemp;
  double? windSpd;
  int? pop;
  String? windCdirFull;
  double? slp;
  double? moonPhaseLunation;
  String? validDate;
  double? appMaxTemp;
  double? vis;
  double? dewpt;
  int? snow;
  double? uv;
  WeatherAPIDataWeather? weather;
  int? windDir;
  String? maxDhi;
  int? cloudsHi;
  int? precip;
  double? lowTemp;
  double? maxTemp;
  int? moonsetTs;
  String? datetime;
  double? temp;
  double? minTemp;
  int? cloudsMid;
  int? cloudsLow;

  WeatherAPIData({
    this.moonriseTs,
    this.windCdir,
    this.rh,
    this.pres,
    this.highTemp,
    this.sunsetTs,
    this.ozone,
    this.moonPhase,
    this.windGustSpd,
    this.snowDepth,
    this.clouds,
    this.ts,
    this.sunriseTs,
    this.appMinTemp,
    this.windSpd,
    this.pop,
    this.windCdirFull,
    this.slp,
    this.moonPhaseLunation,
    this.validDate,
    this.appMaxTemp,
    this.vis,
    this.dewpt,
    this.snow,
    this.uv,
    this.weather,
    this.windDir,
    this.maxDhi,
    this.cloudsHi,
    this.precip,
    this.lowTemp,
    this.maxTemp,
    this.moonsetTs,
    this.datetime,
    this.temp,
    this.minTemp,
    this.cloudsMid,
    this.cloudsLow,
  });
  WeatherAPIData.fromJson(Map<String, dynamic> json) {
    moonriseTs = json["moonrise_ts"]?.toInt();
    windCdir = json["wind_cdir"]?.toString();
    rh = json["rh"]?.toInt();
    pres = json["pres"]?.toDouble();
    highTemp = json["high_temp"]?.toDouble();
    sunsetTs = json["sunset_ts"]?.toInt();
    ozone = json["ozone"]?.toDouble();
    moonPhase = json["moon_phase"]?.toDouble();
    windGustSpd = json["wind_gust_spd"]?.toDouble();
    snowDepth = json["snow_depth"]?.toInt();
    clouds = json["clouds"]?.toInt();
    ts = json["ts"]?.toInt();
    sunriseTs = json["sunrise_ts"]?.toInt();
    appMinTemp = json["app_min_temp"]?.toDouble();
    windSpd = json["wind_spd"]?.toDouble();
    pop = json["pop"]?.toInt();
    windCdirFull = json["wind_cdir_full"]?.toString();
    slp = json["slp"]?.toDouble();
    moonPhaseLunation = json["moon_phase_lunation"]?.toDouble();
    validDate = json["valid_date"]?.toString();
    appMaxTemp = json["app_max_temp"]?.toDouble();
    vis = json["vis"]?.toDouble();
    dewpt = json["dewpt"]?.toDouble();
    snow = json["snow"]?.toInt();
    uv = json["uv"]?.toDouble();
    weather = (json["weather"] != null)
        ? WeatherAPIDataWeather.fromJson(json["weather"])
        : null;
    windDir = json["wind_dir"]?.toInt();
    maxDhi = json["max_dhi"]?.toString();
    cloudsHi = json["clouds_hi"]?.toInt();
    precip = json["precip"]?.toInt();
    lowTemp = json["low_temp"]?.toDouble();
    maxTemp = json["max_temp"]?.toDouble();
    moonsetTs = json["moonset_ts"]?.toInt();
    datetime = json["datetime"]?.toString();
    temp = json["temp"]?.toDouble();
    minTemp = json["min_temp"]?.toDouble();
    cloudsMid = json["clouds_mid"]?.toInt();
    cloudsLow = json["clouds_low"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["moonrise_ts"] = moonriseTs;
    data["wind_cdir"] = windCdir;
    data["rh"] = rh;
    data["pres"] = pres;
    data["high_temp"] = highTemp;
    data["sunset_ts"] = sunsetTs;
    data["ozone"] = ozone;
    data["moon_phase"] = moonPhase;
    data["wind_gust_spd"] = windGustSpd;
    data["snow_depth"] = snowDepth;
    data["clouds"] = clouds;
    data["ts"] = ts;
    data["sunrise_ts"] = sunriseTs;
    data["app_min_temp"] = appMinTemp;
    data["wind_spd"] = windSpd;
    data["pop"] = pop;
    data["wind_cdir_full"] = windCdirFull;
    data["slp"] = slp;
    data["moon_phase_lunation"] = moonPhaseLunation;
    data["valid_date"] = validDate;
    data["app_max_temp"] = appMaxTemp;
    data["vis"] = vis;
    data["dewpt"] = dewpt;
    data["snow"] = snow;
    data["uv"] = uv;
    if (weather != null) {
      data["weather"] = weather!.toJson();
    }
    data["wind_dir"] = windDir;
    data["max_dhi"] = maxDhi;
    data["clouds_hi"] = cloudsHi;
    data["precip"] = precip;
    data["low_temp"] = lowTemp;
    data["max_temp"] = maxTemp;
    data["moonset_ts"] = moonsetTs;
    data["datetime"] = datetime;
    data["temp"] = temp;
    data["min_temp"] = minTemp;
    data["clouds_mid"] = cloudsMid;
    data["clouds_low"] = cloudsLow;
    return data;
  }
}

class WeatherAPI {
/*
{
  "data": [
    {
      "moonrise_ts": 1634594272,
      "wind_cdir": "W",
      "rh": 60,
      "pres": 1009.29,
      "high_temp": 19.9,
      "sunset_ts": 1634596376,
      "ozone": 293.405,
      "moon_phase": 0.985026,
      "wind_gust_spd": 12.5,
      "snow_depth": 0,
      "clouds": 1,
      "ts": 1634529660,
      "sunrise_ts": 1634556206,
      "app_min_temp": 8.8,
      "wind_spd": 3.17652,
      "pop": 0,
      "wind_cdir_full": "west",
      "slp": 1019.4,
      "moon_phase_lunation": 0.43,
      "valid_date": "2021-10-18",
      "app_max_temp": 18.9,
      "vis": 24.096,
      "dewpt": 6.1,
      "snow": 0,
      "uv": 5.33343,
      "weather": {
        "icon": "c01d",
        "code": 800,
        "description": "Clear Sky"
      },
      "wind_dir": 277,
      "max_dhi": null,
      "clouds_hi": 0,
      "precip": 0,
      "low_temp": 8.8,
      "max_temp": 19.9,
      "moonset_ts": 1634552290,
      "datetime": "2021-10-18",
      "temp": 14.6,
      "min_temp": 8.7,
      "clouds_mid": 0,
      "clouds_low": 1
    }
  ],
  "city_name": "Raleigh",
  "lon": "-78.63861",
  "timezone": "America/New_York",
  "lat": "35.7721",
  "country_code": "US",
  "state_code": "NC"
} 
*/

  List<WeatherAPIData?>? data;
  String? cityName;
  String? lon;
  String? timezone;
  String? lat;
  String? countryCode;
  String? stateCode;

  WeatherAPI({
    this.data,
    this.cityName,
    this.lon,
    this.timezone,
    this.lat,
    this.countryCode,
    this.stateCode,
  });
  WeatherAPI.fromJson(Map<String, dynamic> json) {
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <WeatherAPIData>[];
      v.forEach((v) {
        arr0.add(WeatherAPIData.fromJson(v));
      });
      this.data = arr0;
    }
    cityName = json["city_name"]?.toString();
    lon = json["lon"]?.toString();
    timezone = json["timezone"]?.toString();
    lat = json["lat"]?.toString();
    countryCode = json["country_code"]?.toString();
    stateCode = json["state_code"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["city_name"] = cityName;
    data["lon"] = lon;
    data["timezone"] = timezone;
    data["lat"] = lat;
    data["country_code"] = countryCode;
    data["state_code"] = stateCode;
    return data;
  }
}
